
export const testimonial = [
  
  {
    id:1,
    name : "Shafeek",
    brand : "Comfold",
    desc : "Working with Novus has been a game-changer for our business. Their strategic approach and attention to detail have significantly boosted our online presence. They truly understand our brand and audience, delivering exceptional results. We highly recommend their services to anyone looking to elevate their  marketing efforts.",
    color:'#e5f6f2'

  },
  {
    id:3,
    name : "arjun",
    brand : "Cbeeso",
    desc : " I can't speak highly enough about Novus. From the initial consultation to the ongoing campaign management, their creative approach has helped us achieve remarkable ROI on our digital marketing investments. If you're looking for a partner to take your online presence to the next level, look no further than Novus.",
    color: '#FFEBF0'
  },
  {
    id:1,
    name : "arnold",
    brand : "Invex",
    desc : "Working with Novus has been a game-changer for our business. Their strategic approach and attention to detail have significantly boosted our online presence. They truly understand our brand and audience that exceeded our expectations. We highly recommend their services to anyone looking to elevate their digital  efforts.",
    color:'#ffeee8'
  },
]


export const brandBanner = [
   {
    id: 8,
    title : "carousal 1",
           img : "/banner/seller41.png"

  },
   {
    id: 13,
    title : "carousal 1",
    img : "/banner/seller44.png"

  },
 
  {
    id: 3,
    title : "carousal 1",
    img : "/banner/seller48.png"

  },
   {
    id: 1,
    title : "carousal 1",
    img : "/banner/seller50.png"
  },
  {
    id: 6,
    title : "carousal 1",
       img : "/banner/seller26.png"

  },
  {
    id: 14,
    title : "carousal 1",
    img : "/banner/seller45.png"
  },
]



export const social =  [
 
  {
    name: 'linkedin',
    url: '/linkedin.svg',
    href : 'https://www.linkedin.com/company/novus/?viewAsMember=true'
  },
  {
    name: 'instagram',
    url: '/instagram.svg',
    href : 'https://www.instagram.com/novus/?next=%2F'
  },
  {
    name: 'facebook',
    url: '/facebook.svg',
    href:   'https://www.facebook.com/profile.novus'
  },
];

export const HomeExplores = [{
  id: 1,
  title : "perfumes",
  img: "/perfumes/perfume1.jpg"
},
{
  id: 81,
  title : "kids",
  img: "/kids/kid3.jpg"
},
{
  id: 14,
  title : "men",
  img: "/men/m2.jpg"
},
{
  id: 13,
  title : "shoes",
  img: "/shoes/sh5.jpg"
},
{
  id: 11,
  title : "women",
  img: "/women/w9.jpg"
},
{
  id: 12,
  title : "mobiles",
  img: "/mobiles/mob2.jpg"
},
{
  id: 10,
  title : "bicycle",
  img: "/cycles/b3.jpg"
},
]



export const privacySections = [
    {
      title: 'Introduction',
      content: `
The translations provided are generated by AI; in case of any discrepancy or difference, the English version will take precedence over the translation.

This Privacy Policy describes how Novus Designs Private Limited and its affiliates and group entities (collectively referred to as "Novus," "we," "our," or "us") collect, use, share, and process your personal data through https://www.Novus.com, its sub-domains; m-site (hereinafter, collectively referred to as “Platform”).

While you can browse certain sections of our platform without registering, our services and products require registration and are exclusively offered within India. Your personal data is primarily governed by Indian laws and stored in India, however, some of your personal data may be processed or stored in servers located outside of India to ensure efficient service delivery. To avail the products or services within our platform, you are required to explicitly consent to adhere to the guidelines set forth in this Policy, as well as our Terms of Use and any terms specific to certain services or products we offer and agree to be governed by the laws of India including but not limited to the laws applicable to data protection and privacy.
      `
    },
    {
      title: 'Collection and Purpose',
      content: `
We collect your personal data directly from you (e.g., when you visit our Platform); in course of our relationship with you (e.g., if you purchase our products or utilize services); when you make your personal data public (e.g., if you make a public post about us on social media); when you download, install or use any of our Services. You can browse our Platform without registering however once you use Platform or give us your personal data, you may no longer be anonymous to us. We clearly indicate which fields are mandatory for using certain services and which are optional, thereby offering you the choice to decide. We may also receive information about you from third parties (e.g., our delivery partners). We may also create information about you, such as records of your interactions with us or combine data you have provided to us with data obtained from third parties such as social networks and other data collection entities. Novus is not responsible for personal data you volunteer about yourself in the public domains. This Privacy Policy does not cover the practices of third parties who may provide information about you to Novus. Some of the information that we may collect includes but is not limited to are listed below:

- **Registration and Personalisation**: We collect basic identifying information like your name, date of birth, device identifiers, and IP address to personalise your experience, provide the services you request. This includes assisting sellers and business partners in handling and fulfilling orders, enhancing customer experience, resolving disputes, and troubleshooting problems. We also use your data to detect and protect against error, fraud, and other criminal activities.

- **Communication and Order Delivery**: Your address is essential for order delivery. Your telephone number and email ID are used for updates and commercial communications related to your orders and other products and services. We may request permission to access your text messages (SMS), instant messages, contacts, camera, photo gallery, location, and device information for enhancing your experience and providing access to various services. Your access to these services may be affected if permission is not provided.

- **Transaction Processing**: Financial data like bank account details and credit/debit card information are collected to process transactions efficiently.

- **Eligibility Checks**: For certain services, products or events including but not limited to credit and payment products, we require identity verification data such as PAN, GST number, government-issued IDs, credit checks and KYC details which may further be shared with our banking and lending partners.

- **Enhanced User Experience**: To offer specific features on our Platform, we may collect biometric and behavioural data, such as facial features and shopping habits.

- **Loyalty Programs**: If you enrol in our loyalty program or a third-party loyalty program offered by us, we collect personal data such as your name, contact number, and other relevant details for the loyalty program.

- **Marketing and User Experience**: To the extent we use your data for marketing, you have the option to opt-out. We also conduct research and surveys to improve our offerings and may ask for additional demographic and profile data, which is entirely voluntary to provide. This includes attributes like your interests, household or lifestyle information, purchasing behaviour, and preferences. We use this data to tailor your experience at our Platform, providing you with content that we think you might be interested in and to display content according to your preferences.

- **AI Offerings and Model Training**: You may voluntarily opt to use our AI features like the Skin and Hair Analyser, AI Stylist, MyFashionGPT, Maya chatbot etc. Data collected from these features, as well as aggregated data of user behaviour, user analytics, or user-generated content, may be used to train various AI models. While using these AI features, user discretion is advised as some technologies may produce hallucinations or other unexpected results.

- **Customer Support and Personal Correspondence**: Your interactions with our customer support via chat, calls, or emails are recorded for quality assurance and safety. Personal correspondence such as emails or letters, as well as correspondence from third parties about your activities, may be collected into a file specific to you.

- **Community and Affiliate Programs**: For users who enroll onto specific platforms such as the Ultimate Glam Clan, we may collect your Social Media handles. The purpose of this collection is to facilitate communication with you regarding potential influencer engagements to promote us to your audience.

- **Public Forums and User Interactions**: Please be mindful when sharing messages, reviews, or other content in public areas of our Platform. Such information is not only publicly accessible but may also be collected and stored by us for internal use, research, training and compliance purposes. Additionally, with your explicit consent, we may display images you upload to platforms like the Ultimate Glam Clan on our promotional banners and on the profile pages of the products featured in your UGC profile. This is for the purpose of showcasing products on real users to enhance authenticity and for other marketing initiatives.

- **Third-Party Services**: Novus does not control, endorse, or assume responsibility for the privacy practices of third parties, and we encourage you to review their privacy policies. We are not responsible for the privacy practices of third-party partners. It's important to review their privacy policies before sharing information with them.
      `
    },
    {
      title: 'Cookies',
      content: `
We use data collection devices like "cookies" on our Platform to assist with various functionalities. Cookies are small files placed on your hard drive and do not contain personal data. They help us in:

- Analysing web page flow.
- Measuring promotional effectiveness.
- Promoting trust and safety.

We use cookies from third-party partners such as Google Analytics for marketing and analytical purposes. Additionally, you may encounter "cookies" or other similar devices (pixels, web beacons) on certain pages of the Platform that are placed by third parties not partnered with us. We do not control the use of cookies by third parties.

For partnered third-party cookies, you can read more about how Google uses your Personal Information [here](https://policies.google.com/privacy), and opt-out of Google Analytics [here](https://tools.google.com/dlpage/gaoptout).

Most cookies are "session cookies," deleted automatically at the end of a session. You are free to decline our cookies if your browser permits, although doing so may disable certain features on the Platform and require more frequent re-entry of your password.
      `
    },
    {
      title: 'Sharing',
      content: `
We may share your personal data internally within the Flipkart Group, our other corporate entities, and affiliates including Flipkart Advanz Private Limited, Scapic Innovations Private Limited, and other Flipkart affiliates, related companies, including Credit Bureaus and business partners (such as UPI platform), for purposes of providing products and services offered by such Flipkart group companies and affiliates and related companies, such as, personal loans offered by Scapic Innovations Private Limited through its lending partners, insurance, the deferred payment options, Flipkart PayLater offered by Flipkart Advanz Private Limited through its lending partners. These group companies, affiliates and related parties may share such information with their own affiliates, business partners and other third parties for the purpose of conducting the required checks, namely for the purpose of credit underwriting, providing you their products and services and may market to you as a result of such sharing. These entities and affiliates may market to you as a result of such sharing unless you explicitly opt-out.

Your personal and sensitive information may also be disclosed with third parties, including AI System providers for the following reasons:

- To provide you access to our services and products
- To personalise customer engagement, curated product or service recommendations, and other outreach activities designed to align with your interests and preferences.
- To comply with legal obligations.
- To enforce our user agreement.
- To facilitate our marketing and advertising activities.
- To prevent, detect, mitigate, and investigate fraudulent or illegal activities related to our services

We may also disclose your personal data to third parties, such as our sellers, business partners. This disclosure may be required for us to provide you access to our products and services; for fulfillment of your orders; for enhancing your experience; for providing feedback on products; to collect payments from you; to comply with our legal obligations; to conduct market research or surveys; to enforce our Terms of Use; to facilitate our marketing and advertising activities; to analyze data; for customer service assistance; to prevent, detect, mitigate, and investigate fraudulent or illegal activities related to our product and services. We also share certain personal data with sellers who may be located outside of India such as international brands. Regardless of where your data is processed or shared, it remains subject to the protections and guidelines of this Privacy Policy.

In addition, we may share your personal data with business partners and third-parties who offer services to us or to whom we provide our products or services to enable them to offer, advertise, personalise your browsing experience and customise various aspects of the user journey such as the checkout flow, auto-filling sign-up details to facilitate a faster checkout process, or promote their own products and services to you and this may include, without limitation, conducting marketing campaigns, personalised customer engagement, curated product or service recommendations, and other outreach activities designed to align with your interests and preferences.

In case of a business transaction like a merger, acquisition, or restructuring, your data may be shared or sold to the new business entity, should such a transaction occur, that other business entity (or the new combined entity) will be required to follow this privacy policy with respect to your personal data.
      `
    },
    {
      title: 'Links to Other Sites',
      content: `
Our Platform links to other websites that may collect personal data about you. Novus is not responsible for the privacy practices or the content of those linked websites.
      `
    },
    {
      title: 'Security Precautions',
      content: `
We maintain reasonable security practices and procedures to protect your personal data from unauthorized access, damage, use, modification, disclosure or impairment of the information under our control. Whenever you access your account information, we offer the use of a secure server. The transmission of information is not completely secure for reasons beyond our control. We adopt industry standard security measures and keep updating our systems from time to time to protect your personal data against any hacking or virus dissemination. However, by using the Platform, the users accept the security implications of data transmission over the internet and the World Wide Web which cannot always be guaranteed as completely secure, and therefore, there would always remain certain inherent risks regarding use of the Platform. Users are responsible for ensuring the protection of login and password records for their account. We have policies and procedures in place to tackle incidents of information security breach, which enables the incident response team to detect, analyse, contain, remediate and recover from information security breach incidents.
      `
    },
    {
      title: 'Choice/Opt-Out',
      content: `
We provide all users with the opportunity to opt-out of receiving non-essential (promotional, marketing-related) communications from us after setting up an account. If you do not wish to receive promotional communications from us, then please unsubscribe by clicking on the unsubscribe link in the email or visit our Help Center at Unsubscribe.
      `
    },
    {
      title: 'Advertisements',
      content: `
We use third-party advertising companies to serve ads when you visit our Platform. These companies may use information (not including your name, address, email address, or telephone number) about your visits to this Platform and other websites in order to provide advertisements about goods and services of interest to you. You have an option to opt-out from tracking of personalised advertising using the “Opt out of Ads Personalization” settings using your device’s settings application. Novus will have no access to your GAID once you select this feature.
      `
    },
    {
      title: 'Use of Children Information',
      content: `
Use of our Platform is available only to persons who can form a legally binding contract under the Indian Contract Act, 1872. We do not knowingly solicit or collect personal data from children under the age of 18 years. If you have shared any personal data of children under the age of 18 years, you represent that you have the authority to do so and permit us to use the information in accordance with this Privacy Policy.
      `
    },
    {
      title: 'Data Retention',
      content: `
We retain your personal data for a period no longer than is required for the purpose for which it was collected or as required under any applicable law. However, we may retain data related to you if there is a legal obligation to retain the data; if required to comply with any applicable statutory or regulatory retention requirement by law; if we believe it may be necessary to prevent fraud or future abuse; to enable Novus to exercise its legal rights and/or defend against legal claims. We may continue to retain your data in anonymised form for analytical and research purposes.
      `
    },
    {
      title: 'Your Rights',
      content: `
We are committed to providing you with control over your personal data. You can visit our Privacy Centre, a self-serve portal designed to help you easily manage your data and exercise your rights. Through the Privacy Centre, you can:

- Request a copy of your personal data held by us.
- Check the status of any existing data requests.
- Edit or update your personal data.
- Request the deletion of your account.

To exercise any rights beyond those available in the self-serve portal, such as withdrawing consent or appointing a nominee, you may contact our customer support team using the details provided below.
      `
    },
    {
      title: 'Changes to this Privacy Policy',
      content: `
Please check our Privacy Policy periodically for changes. We may update this Privacy Policy to reflect changes to our information practices. We will alert you to significant changes by posting the date our Privacy Policy got last updated, placing a notice on our Platform, or by sending you an email when we are required to do so by applicable law.
      `
    }
  ];


export const termsSections = [
    {
      title: 'Introduction',
      content: `
This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.

This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name ("Website"), including the related mobile site and mobile application (hereinafter referred to as "Platform").

The Platform is owned by Novus Internet Private Limited, a company incorporated under the Companies Act, 1956 with its registered office at Buildings Alyssa, Begonia & Clover, Embassy Tech Village, Outer Ring Road, Devarabeesanahalli Village, Bengaluru – 560103, Karnataka, India and its branch offices at 2nd Floor, Block F (Flora), Embassy Tech Village, Outer Ring Road, Devarabeesanahalli Village, Bengaluru-560103, Karnataka, India and; 447/C, 12th Main, 4th Block, Koramangala, Bengaluru-560034, Karnataka, India (hereinafter referred to as "Novus").
      `
    },
    {
      title: 'Terms of Use',
      content: `
Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with Novus Internet Private Limited and these terms and conditions including the policies constitute Your binding obligations, with Novus.

For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Platform by providing Registration Data while registering on the Platform as Registered User using the computer systems. Novus allows the User to surf the Platform or making purchases without registering on the Platform. The term "We", "Us", "Our" shall mean Novus Internet Private Limited.

ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Novus Policies (including but not limited to Privacy Policy available at Privacy) as amended from time to time.
      `
    },
    {
      title: 'Membership Eligibility',
      content: `
Transaction on the Platform is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the Platform. If you are a minor i.e. under the age of 18 years, you may use the Platform or access content on the Platform only under the supervision and prior consent/ permission of a parent or legal guardian.

As a minor if you wish to transact on the Platform, such transaction on the Platform may be made by your legal guardian or parents. Novus reserves the right to terminate your membership and / or refuse to provide you with access to the Platform if it is brought to Novus's notice or if it is discovered that You are under the age of 18 years and transacting on the Platform.
      `
    },
    {
      title: 'Your Account and Registration Obligations',
      content: `
If You use the Platform, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Platform and refuse to provide You with access to the Platform.

Your mobile phone number and/or e-mail address is treated as Your primary identifier on the Platform. It is your responsibility to ensure that Your mobile phone number and your email address is up to date on the Platform at all times. You agree to notify Us promptly if your mobile phone number or e-mail address changes by updating the same on the Platform through a onetime password verification.

You agree that Novus shall not be liable or responsible for the activities or consequences of use or misuse of any information that occurs under your Account in cases, including, where You have failed to update Your revised mobile phone number and/or e-mail address on the Website Platform.

If You share or allow others to have access to Your account on the Platform (“Account”), by creating separate profiles under Your Account, or otherwise, they will be able to view and access Your Account information. You shall be solely liable and responsible for all the activities undertaken under Your Account, and any consequences there from.

You must maintain confidentiality of the account information and for all the activities that occur under Your account. You must not share your login details, ie, username and password of Your account with any other person, else it would be considered breach of this Terms of Use.

You agree to: (a) ensure that You successfully log out from Your account at the end of each session; and (b) immediately notify Novus of any unauthorized use of Your account. If there is reason to believe that there is likely to be a breach of security or misuse of Your account, We may request You to change the password or we may suspend Your account without any liability to Novus, for such period of time as we deem appropriate in the circumstances. We shall not be liable for any loss or damage arising from Your failure to comply with this provision.

You will have access to other apps owned by Novus group companies through the same login username and password. You agree to have single login access to all the apps owned by Novus group companies.
      `
    },
    {
      title: 'Communications',
      content: `
When You use the Platform or send emails or other data, information or communication to us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required. We may communicate with you by email or by such other mode of communication, electronic or otherwise.
      `
    },
    {
      title: 'Platform for Transaction and Communication',
      content: `
The Platform enables the Buyer and Seller to transact on the Platform. Novus is not and cannot be a party to or control in any manner any transaction between the Platform's Users.

Henceforward:

All commercial/contractual terms are offered by and agreed to between Buyers and Sellers alone. The commercial/contractual terms include without limitation price, shipping costs, payment methods, payment terms, date, period and mode of delivery, warranties related to products and services and after sales services related to products and services. Novus does not have any control or does not determine or advise or in any way involve itself in the offering or acceptance of such commercial/contractual terms between the Buyers and Sellers. All discounts, offers (including exchange offers) are by the Seller/Brand and not by Novus.

Placement of order by a Buyer with Seller on the Platform is an offer to buy the product(s) in by the Buyer to the Seller and it shall not be construed as Seller's acceptance of Buyer's offer to buy the product(s) ordered. The Seller retains the right to cancel any such order placed by the Buyer, at its sole discretion and the Buyer shall be intimated of the same by way of an email/SMS. Any transaction price paid by Buyer in case of such cancellation by Seller, shall be refunded to the Buyer. Further, the Seller may cancel an order wherein the quantities exceed the typical individual consumption. This applies both to the number of products ordered within a single order and the placing of several orders for the same product where the individual orders comprise a quantity that exceeds the typical individual consumption. What comprises a typical individual's consumption quantity limit shall be based on various factors and at the sole discretion of the Seller and may vary from individual to individual.

Novus does not make any representation or Warranty as to specifics (such as quality, value, salability, etc) of the products or services proposed to be sold or offered to be sold or purchased on the Platform. Novus does not implicitly or explicitly support or endorse the sale or purchase of any products or services on the Platform. Novus accepts no liability for any errors or omissions, whether on behalf of itself or third parties.

Novus is not responsible for any non-performance or breach of any contract entered into between Buyers and Sellers. Novus cannot and does not guarantee that the concerned Buyers and/or Sellers will perform any transaction concluded on the Platform. Novus shall not and is not required to mediate or resolve any dispute or disagreement between Buyers and Sellers.

Novus does not make any representation or warranty as to the item-specifics (such as legal title, creditworthiness, identity, etc) of any of its Users. You are advised to independently verify the bona fides of any particular User that You choose to deal with on the Platform and use Your best judgment in that behalf.

Novus does not at any point of time during any transaction between Buyer and Seller on the Platform come into or take possession of any of the products or services offered by Seller nor does it at any point gain title to or have any rights or claims over the products or services offered by Seller to Buyer.

At no time shall Novus hold any right, title or interest over the products nor shall Novus have any obligations or liabilities in respect of such contract entered into between Buyers and Sellers. Novus is not responsible for unsatisfactory or delayed performance of services or damages or delays as a result of products which are out of stock, unavailable or back ordered.

The Platform is only a platform that can be utilized by Users to reach a larger base to buy and sell products or services. Novus is only providing a platform for communication and it is agreed that the contract for sale of any of the products or services shall be a strictly bipartite contract between the Seller and the Buyer.

At no time shall Novus hold any right, title or interest over the products nor shall Novus have any obligations or liabilities in respect of such contract.

Novus is not responsible for unsatisfactory or delayed performance of services or damages or delays as a result of products which are out of stock, unavailable or back ordered.

Select products offered by sellers may be eligible for business purchases on the Platform.

Upon Your purchase of product(s) eligible for business purchases, You may be able to avail the benefits of GST input tax credit. Accordingly, at your request, an invoice containing the GSTIN as provided by You ("Tax Invoice") shall be issued to You by the Seller(s) selling such products.

* GST invoice will have, inter alia, the following details printed on it: -GSTIN associated with your registered business, as provided by you

* Entity name of your registered business, as provided by you

* Not all products are eligible for business purchases on the Platform and the same is solely at the discretion of the Sellers. You will be able to view the eligibility of Tax Invoice on the product page on the Platform.

* For seamless availment of input tax credit, kindly mention the delivery address as the address which is mentioned as the registered place of business as per the records of GST authority. Please note that availment of input tax credit is subject to provisions of GST Act and rules.

* The delivery and billing addresses will be required to be the same, please note that input tax credit will be denied by GST authority if the delivery address and GSTIN in the GST invoice are of different states.

* If GSTIN and/or business entity details are not provided by You, it will be presumed that it is a personal purchase and not a business purchase.

* Novus is not responsible to verify the correctness of the GSTIN and/or entity name provided by You and You shall be entirely responsible to provide the accurate details.

* Novus and Seller shall not entertain any request for any revision in the GST Invoice. Novus and Seller shall not be liable for Your default including for reasons associated with details provided by You.

* Novus will not be liable in case You are not able to avail input tax credit or if input tax credit is denied to You for any reason whatsoever.

* You shall be solely liable for all compliances required under applicable laws.

* You agree to indemnify and hold Novus and Seller harmless from all losses, claims, costs, expenses, suits, proceedings, or any other liability including any third-party claims (including any penalties imposed by governmental authorities) arising out of or in connection with (1) the GSTIN and/or entity name provided by you or the input tax credit claimed by you or your use or misuse of the GST Invoice and (2) your non-compliance with the applicable laws or (3) your use or misuse of any third-party’s details including GSTIN.

* Novus has the right to not allow business purchases on the Platform to You if a fraudulent activity is identified.

* Seller reserves the right to not issue Tax Invoice or issue a credit note against an already issued Tax Invoice to cancel the transaction, if any fraudulent activity is identified.

You shall independently agree upon the manner and terms and conditions of delivery, payment, insurance etc. with the seller(s) that You transact with.

Disclaimer: Pricing on any product(s) as is reflected on the Platform may due to some technical issue, typographical error or product information published by seller may be incorrectly reflected and in such an event seller may cancel such your order(s).

You release and indemnify Novus and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions of the Users of the Platform and specifically waive any claims that you may have in this behalf under any applicable law. Notwithstanding its reasonable efforts in that behalf, Novus cannot take responsibility or control the information provided by other Users which is made available on the Platform. You may find other User's information to be offensive, harmful, inconsistent, inaccurate, or deceptive. Please use caution and practice safe trading when using the Platform.

Please note that there could be risks in dealing with underage persons or people acting under false pretense.
      `
    },
    {
      title: 'Charges',
      content: `
Novus may charge a nominal fee for browsing and buying on the Platform. Novus reserves the right to change its Fee Policy from time to time. In particular, Novus may at its sole discretion introduce new services/fees and modify some or all of the existing services/fees offered on the Platform. In such an event, Novus reserves the right to introduce fees for the new services offered or amend/introduce fees for existing/new services, as the case may be. Changes to the Fee Policy shall be posted on the Platform and such changes shall automatically become effective immediately after they are posted on the Platform. Unless otherwise stated, all fees shall be quoted in Indian Rupees. You shall be solely responsible for compliance of all applicable laws including those in India for making payments to Novus Internet Private Limited.

**What is the platform fee?**

Fee levied by Novus to sustain the efficient operations and continuous improvement of the platform, for a hassle-free app experience.

**Refund of Platform Fee**

a) If the order is lost or undelivered to the preferred location, the complete order amount will be refunded if paid online, including the platform fee.

b) If a customer cancels an order partially or returns part of an order, platform charges will be refunded as allocated to the item being returned/canceled.

c) Platform charges will be refunded in case of a full order cancellation.

**Convenience Fee (Novus Flights)**

For availing the travel booking services on the Platform, Novus reserves the right to charge certain fees in the nature of convenience fees or service fees in addition to the cost of booking as charged by the service providers. Novus further reserves the right to alter any and all fees from time to time. Any such additional fees, including fee towards any modifications thereof, will be displayed to customer before confirming the booking or collecting the payment from such customer. In the event of short charging of the booking amount, taxes, statutory fee, convenience fee etc., owing to any technical error or other reason, Novus shall reserve the right to deduct, charge or claim the balance amount from the customer and the customer shall pay such balance amount to Novus. In the event where the charge is claimed prior to the utilization of the booking, Novus will be at liberty to cancel such bookings if the amount is not paid before the utilization date. Novus is not responsible for any refunds in connection with any services offered by any person on the Novus platform (except for passing on such refunds when received from such persons to customers), other than refunds of convenience fees paid made to Novus for the services it provides to customers (subject to such refund requests being in compliance with these Terms and Conditions and with the terms of the applicable ticket / booking).

By agreeing to the Terms of Use, you agree to engage the services of a transport service provider (“Transporter”) (facilitated by Novus) for transportation of products from the location of the seller, where it is handed over to the Transporter and it is delivered to your location. Such movement of products is on your account and the Transporter is only responsible for transportation of products. In lieu of these services, you will be liable to pay “GT Charges” for delivery of your products. You agree that Novus is authorized to collect the “GT charges” from you on behalf of the Transporter. The GT Charges may vary from order to order, which will be determined on multiple factors, which shall include but not be limited to order value, distance and time of the day. Novus will inform you of the GT Charges that may apply to you, at the time of placing the order, and you shall be liable to pay GT Charges incurred for your order.

In case the products are ultimately returned by you, the GT Charges (if already collected) will be refunded within the same timelines from the day the refund amount is processed and the amount will be credited to your selected mode of payment.

You acknowledge that all purchases of the products are direct transactions between you and the Seller. The Transporter is not a party to the sale and assumes no title, interest, or rights in the products. Ownership transfers to you when the products are handed over to the Transporter by the Seller. Once the Seller hands over the products to the Transporter for delivery, the ownership of, products is immediately transferred to you. The Transporter’s role is strictly limited to providing logistics and delivery services, and the Transporter shall not be considered a buyer or seller of the products. The contract of sale exists solely between you and the Seller.

You agree that once you accept delivery of the products at the delivery location, it shall be deemed that the Transporter has completed all its contractual obligations as Product a Logistics service provider. Your acceptance of delivery of products shall constitute deemed approval of the fact that the consignment has been received in full and intact condition.

The Transporter is a “ Goods Transport Agency” under the GST laws, GT Charges will be charged along with applicable taxes (wherever applicable).

The Transporter shall, for booking of the consignment to be transported, issue a Consignment Note, which will also include the terms and conditions governing the carriage, in addition to the applicable Terms of Use mentioned herein. You are encouraged to refer to the additional terms and conditions set out in the Consignment Note, which shall be made available to you in your order page.

The Transporter shall not be liable for any delay in pickup, mis-delivery, non-delivery or loss or damage to shipment caused on account of an act of God, force majeure product or any other cause reasonably beyond the control of the Transporter.

Any time of arrival/delivery provided at booking by Novus is an estimate only and the Transporter has no role in providing such estimate. The Transporter shall not be bound by any time-commitments made by Novus to the customer.
      `
    },
    {
      title: 'Use of the Platform',
      content: `
You agree, undertake and confirm that Your use of Platform shall be strictly governed by the following binding principles:

You shall not host, display, upload, modify, publish, transmit, update or share any information which:
(a) belongs to another person and to which You do not have any right to;

(b) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libelous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to "indecent representation of women" within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;

(c) is misleading in any way;

(d) is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, paedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual;

(e) harasses or advocates harassment of another person;

(f) involves the transmission of "junk mail", "chain letters", or unsolicited mass mailing or "spamming";

(g) promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libellous;

(h) infringes upon or violates any third party's rights [including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address or phone number) or rights of publicity];

(i) promotes an illegal or unauthorized copy of another person's copyrighted work (see "Copyright complaint" below for instructions on how to lodge a complaint about uploaded copyrighted material), such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices;

(j) contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);

(k) provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;

(l) provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses;

(m) contains video, photographs, or images of another person (with a minor or an adult).

(n) tries to gain unauthorized access or exceeds the scope of authorized access to the Platform or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Platform or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;

(o) engages in commercial activities and/or sales without Our prior written consent such as contests, sweepstakes, barter, advertising and pyramid schemes, or the buying or selling of "virtual" products related to the Platform. Throughout this Terms of Use, Novus's prior written consent means a communication coming from Novus's Legal Department, specifically in response to Your 이메일로 보내기 request, and specifically addressing the activity or conduct for which You seek authorization;

(p) solicits gambling or engages in any gambling activity which We, in Our sole discretion, believes is or could be construed as being illegal;

(q) interferes with another USER's use and enjoyment of the Platform or any other individual's User and enjoyment of similar services;

(r) refers to any Platform or URL that, in Our sole discretion, contains material that is inappropriate for the Platform or any other Platform, contains content that would be prohibited or violates the letter or spirit of these Terms of Use.

(s) harm minors in any way;

(t) infringes any patent, trademark, copyright or other proprietary rights or third party's trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen products;

(u) violates any law for the time being in force;

(v) deceives or misleads the addressee/ users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;

(w) impersonate another person;

(x) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;

(y) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.

(z) shall not be false, inaccurate or misleading;

(aa) shall not, directly or indirectly, offer, attempt to offer, trade or attempt to trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force.

(ab) shall not create liability for Us or cause Us to lose (in whole or in part) the services of Our internet service provider ("ISPs") or other suppliers;

You shall not use any "deep-link", "page-scrape", "robot", "spider" or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Platform or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the Platform or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Platform. We reserve Our right to bar any such activity.

You shall not attempt to gain unauthorized access to any portion or feature of the Platform, or any other systems or networks connected to the Platform or to any server, computer, network, or to any of the services offered on or through the Platform, by hacking, password "mining" or any other illegitimate means.

You shall not probe, scan or test the vulnerability of the Platform or any network connected to the Platform nor breach the security or authentication measures on the Platform or any network connected to the Platform. You may not reverse look-up, trace or seek to trace any information on any other User of or visitor to Platform, or any other customer, including any account on the Platform not owned by You, to its source, or exploit the Platform or any service or information made available or offered by or through the Platform, in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than Your own information, as provided for by the Platform.

You shall not make any negative, denigrating or defamatory statement(s) or comment(s) about Us or the brand name or domain name used by Us including the terms Novus, Flipcart, Novus.com, or otherwise engage in any conduct or action that might tarnish the image or reputation, of Novus or sellers on platform or otherwise tarnish or dilute any Novus's trade or service marks, trade name and/or goodwill associated with such trade or service marks, trade name as may be owned or used by us. You agree that You will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Platform or Novus's systems or networks, or any systems or networks connected to Novus.

You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Platform or any transaction being conducted on the Platform, or with any other person's use of the Platform.

You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal You send to Us on or through the Platform or any service offered on or through the Platform. You may not pretend that You are, or that You represent, someone else, or impersonate any other individual or entity.

You may not use the Platform or any content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of Novus and / or others.

You shall at all times ensure full compliance with the applicable provisions of the Information Technology Act, 2000 and rules thereunder as applicable and as amended from time to time and also all applicable Domestic laws, rules and regulations (including the provisions of any applicable Exchange Control Laws or Regulations in Force) and International Laws, Foreign Exchange Laws, Statutes, Ordinances and Regulations (including, but not limited to Sales Tax/VAT, Income Tax, Octroi, Service Tax, Central Excise, Custom Duty, Local Levies) regarding Your use of Our service and Your listing, purchase, solicitation of offers to purchase, and sale of products or services. You shall not engage in any transaction in an item or service, which is prohibited by the provisions of any applicable law including exchange control laws or regulations for the time being in force.

Solely to enable Us to use the information You supply Us with, so that we are not violating any rights You might have in Your Information, You agree to grant Us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights or any other rights You have in Your Information, in any media now known or not currently known, with respect to Your Information. We will only use Your information in accordance with the Terms of Use and Privacy Policy applicable to use of the Platform.

From time to time, You shall be responsible for providing information relating to the products or services proposed to be sold by You. In this connection, You undertake that all such information shall be accurate in all respects. You shall not exaggerate or over emphasize the attributes of such products or services so as to mislead other Users in any manner.

You shall not engage in advertising to, or solicitation of, other Users of the Platform to buy or sell any products or services, including, but not limited to, products or services related to that being displayed on the Platform or related to us. You may not transmit any chain letters or unsolicited commercial or junk email to other Users via the Platform. It shall be a violation of these Terms of Use to use any information obtained from the Platform in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to another person other than Us without Our prior explicit consent. In order to protect Our Users from such advertising or solicitation, We reserve the right to restrict the number of messages or emails which a user may send to other Users in any 24-hour period which We deems appropriate in its sole discretion. You understand that We have the right at all times to disclose any information (including the identity of the persons providing information or materials on the Platform) as necessary to satisfy any law, regulation or valid governmental request. This may include, without limitation, disclosure of the information in connection with investigation of alleged illegal activity or solicitation of illegal activity or in response to a lawful court order or subpoena. In addition, We can (and You hereby expressly authorize Us to) disclose any information about You to law enforcement or other government officials, as we, in Our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that may involve personal injury.

We reserve the right, but has no obligation, to monitor the materials posted on the Platform. Novus shall have the right to remove or edit any content that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these Terms of Use. Notwithstanding this right, YOU REMAIN SOLELY RESPONSIBLE FOR THE CONTENT OF THE MATERIALS YOU POST ON THE PLATFORM AND IN YOUR PRIVATE MESSAGES. Please be advised that such Content posted does not necessarily reflect Novus views. In no event shall Novus assume or have any responsibility or liability for any Content posted or for any claims, damages or losses resulting from use of Content and/or appearance of Content on the Platform. You hereby represent and warrant that You have all necessary rights in and to all Content which You provide and all information it contains and that such Content shall not infringe any proprietary or other rights of third parties or contain any libelous, tortious, or otherwise unlawful information.

Your correspondence or business dealings with, or participation in promotions of, advertisers found on or through the Platform, including payment and delivery of related products or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between You and such advertiser. We shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such advertisers on the Platform.

It is possible that other users (including unauthorized users or "hackers") may post or transmit offensive or obscene materials on the Platform and that You may be involuntarily exposed to such offensive and obscene materials. It also is possible for others to obtain personal information about You due to your use of the Platform, and that the recipient may use such information to harass or injure You. We does not approve of such unauthorized uses, but by using the Platform You acknowledge and agree that We are not responsible for the use of any personal information that You publicly disclose or share with others on the Platform. Please carefully select the type of information that You publicly disclose or share with others on the Platform.

Novus shall have all the rights to take necessary action and claim damages that may occur due to your involvement/participation in any way on your own or through group/s of people, intentionally or unintentionally in DoS/DDoS (Distributed Denial of Services).
      `
    },
    {
      title: 'Prescription and Non-Prescription Drugs',
      content: `
The information on this website is not intended or implied to be a substitute for professional medical advice, diagnosis or treatment. All content, including text, graphics and information, contained on or available through this Platform is for general information purposes only. Novus makes no representation and assumes no responsibility for the accuracy of information contained on or available through this website and such information is subject to change without notice. You are encouraged to confirm any information obtained from or through this website with other sources and review all information regarding any medical condition or treatment with your physician. NEVER DISREGARD PROFESSIONAL MEDICAL ADVICE OR DELAY SEEKING MEDICAL TREATMENT BECAUSE OF SOMETHING YOU HAVE READ ON OR ACCESSED THROUGH ANY WEBSITE.

Novus does not recommend, endorse, or make any representation about the efficacy, appropriateness or suitability of any specific products, procedures, treatments, opinions or other information that may be contained on or available through this website.
      `
    },
    {
      title: 'Diagnostic Services',
      content: `
Novus facilitates the Users to avail diagnostic test/ packages facilities offered by Third Party Service Providers through the Platform. Such Third Party Service Providers may also offer other services in relation to the diagnostic test/package facilities including but not limited to sample collection, home collection, conducting tests, generating, and delivering lab reports etc (collectively, "Diagnostic Services"). Novus is not and shall not be responsible for any Diagnostic Services offered, performed or delivered by the Third Party Service Providers and does not deal with any of Third Party Service Providers' client or patient managed by Third Party Labs through the Website and only provides facilitation Services to the Users through the Website.

Notwithstanding anything to the contrary contained herein, Third Party Service Providers alone shall be liable for dealings and interaction with Users contacted or managed through the Website and Novus shall have no liability or responsibility in this regard. Novus does not endorse any tests included in the Diagnostic Services nor guarantees or makes any representation with respect to the correctness, completeness or accuracy of the tests conducted and reports generated by the Third Party Service Providers. Third Party Service Providers are solely responsible for ensuring compliance with laws applicable to the provision of Diagnostics Services by them.
      `
    },
    {
      title: 'Teleconsultation Services',
      content: `
For products and services which are required to be prescribed by qualified professionals under law, Novus allows processing of such orders on the website only on confirmation by the Sellers that a valid prescription has been uploaded by you. In cases where the prescriptions uploaded by you are invalid, illegible, or expired or if prescription is not uploaded by you, we may, through third-party vendors connect You with third-party professionals (“Professional”) who have represented that they have the requisite qualifications under law and are suitable to deliver the health care advice that may be required to generate the prescription based on medical advice, in case of invalid/illegible/expired prescription or issue a prescription in case prescription is not uploaded by you, based on the information that You provide to them ("Teleconsultation Services"). As per your medical evaluation, the decision to generate a prescription or not shall be the sole responsibility of the Registered Medical Professional based on his/her discretion.

You agree and acknowledge that you will be redirected to Teleconsultation Services only in limited cases where prescription validation or prescription issuance is required, and they should not be treated as a replacement for obtaining medical advice from your doctor or uploading valid prescriptions on the website. The words “Your Physician” or “Your Doctor” or “Healthcare Provider” or similar words on the Website, shall mean any registered medical Professional with whom the User has a doctor- patient relationship off the website. The Teleconsultation Services and any issue or non-issue of prescription or issue of alternate drugs in the prescription will be at the sole discretion of the Professional and Novus has no relation to or influence on the Teleconsultation Services or the Professionals. It may be determined by the Professional that the Teleconsultation Services are not the right mode for evaluating or diagnosing your medical condition or that a prescription cannot be issued through the Consultation Services, in which case, the order may not be processed any further on the website as orders requiring prescription are not processed without a valid prescription. Novus shall not be responsible for processing of such orders, and you agree that such situations do not amount to a deficiency in services of the website. Further, the Professional is also entitled under law to determine the medium of such Consultation Services, whether through text, audio or video media, in which case you provide your explicit consent to receive the Consultation Services through the medium determined by Professional, failing which the Professional has the right to refuse the Consultation Services. You agree and acknowledge that Novus shall not be responsible for any loss, damage, injury, inconvenience caused to you or any other party due to or arising out of, the refusal of Consultation Services by the Professionals or due to unavailability of the Consultation Services at any time by the third-party vendor.

The Consultation Services are provided on 'as is' or 'as available' basis only, without any warranties or representations from Novus. Therefore, You are free to confirm the advice rendered through the Consultation services with Your Doctor. You agree and acknowledge that the third-party vendor through which You are connected with the Professionals for Consultation Services as well as the Professionals themselves are independent contractors, whose services are being availed by You upon Your implied/ explicit consent and hence, Novus, in no event, shall be directly or vicariously liable for any advice, medical consultancy or any other loss arising pursuant to Your engagement with such third parties. Your reliance on such Consultation Services, Professionals, medical advice and/or prescriptions issued pursuant to the Consultation Services is solely Your responsibility and at Your sole discretion, and Novus assumes no responsibility and/or liability in relation to Your consultation/communication with such Professionals, including but not limited to the quality of services offered by such Professionals, which shall at all times be at Your sole risk and responsibility.

Further, it is Your responsibility for ensuring that the information submitted is accurate and the Novus shall not make any effort to validate any information provided by You for using the Consultation Services. The Professionals will not be examining You physically and hence it shall be your responsibility to furnish all such information and medical history as sought for by the Professionals to enable them to issue a valid prescription pursuant to the Consultation Services. In case of your inability or refusal to share appropriate and sufficient information required by the Professionals, the Professionals are enabled under law to refuse to provide the Consultation Services.

In case your account is used to attend a teleconsultation session by any person other than such person for whom the teleconsultation is conducted/prescription is generated/order is placed, requisite documentation under the law authorizing the person attending the teleconsultation session, must be produced whenever required by any authorities.

By accepting these terms and conditions, You give your explicit consent for processing of your order on the website basis the prescriptions issued by the Professionals pursuant to the Consultation Services. The Professionals at their sole discretion and professional judgment may prescribe alternate drugs or medicine than the ones present in the original invalid prescription uploaded by you. You give your explicit consent for your order to be processed on the website basis prescriptions containing alternate drugs, provided such alternate drugs are made available by the Sellers on the website.

We assume no responsibility and/ or liability in relation to the dispensation of the medicines, which shall at all times be at the sole responsibility of the Sellers supplying the medicines to You. Reliance on any information provided on the Website is solely at Your own risk. You should follow the advice of Your Doctor at all times. The Consultation Services are not for use in medical emergencies or for critical health situations and may not be the best solution where a face-to-face consultation is required. In case of emergencies, you should call Your nearest doctor/hospital or any related helpline and seek immediate medical assistance without any delay and should under no circumstances, delay seeking advice from Your nearest doctor/hospital on account of something that the Professional may have prescribed or You may have heard/viewed on the Website.

Novus in no event recommends or endorses any specific medicines, tests, physicians, products, procedures, opinions, or other information that may be provided by the Professional and the Novus bears no responsibility or liability for the correctness and genuineness of any such advice or prescriptions provided by the Professional, and the Professional shall solely be responsible and liable for the same. The opinions, statements, provided by the Professionals shall not reflect the opinions of Novus, its affiliates etc. Novus also makes no warranty that the Consultation Services will meet Your requirements, or that the Consultation Service(s) will be uninterrupted, timely, secure, or error free. You understand and agree that Novus will not be liable for your interactions and associated issues with the Professional; the ability or intent of the Professionals, in fulfilling their obligations towards you; any wrong medication or quality of treatment being given by the Professionals, or any medical negligence on part of the Professionals; inappropriate treatment, or similar difficulties or any type of inconvenience suffered by you due to a failure on the part of the Professional to provide the Consultation Services. In the event of any non-compliance or malpractice by the Professionals, You affirm that You will bring to our immediate attention, any such incidence, for us to take necessary actions required under applicable laws and raise it with the third-party vendors. Further, You affirm that You shall not take any action against the Novus for any acts (or omission) of the Practitioners.

Further, the recordings and logs of the Consultation Services may be retained by the third-party vendors as per their or Professionals as required under law. Kindly refer to the policies followed by the third-party vendors or consult the Professionals on the nature and extent of data retained by them. It is clarified that Novus does not have access to any exchange, interaction, information, data, medical history etc., that you may share with the Professionals as part of the Consultation Services or the recordings of the Consultation Services sessions. Please see our privacy policy page, for more information on storage, use, and protection of sensitive data and personal information that may be included in prescriptions that are redirected by the Professionals to the website.

You agree and confirm:

That you agree to ensure full compliance with the applicable provisions of the Telemedicine Practice Guidelines, Drugs and Cosmetics Act, 1940, the Drugs Rules, 1945, the Drugs and Magic Remedies (Objectionable Advertisements) Act, 1954 as amended from time to time. That you shall not engage in any transaction which is prohibited by the provisions of any applicable law including the Drugs and Cosmetics Act, 1940, and the Drugs Rules, 1945, as amended from time to time.

You understand and agree that Novus provides only information and knowledge and acts as a bridge between users and the Sellers. All commercial/contractual terms and agreements are between users and Sellers. Novus is a communication medium. All orders are accepted and fulfilled by independent licensed retail chemists subject to verification of Valid Prescription by the said chemist. By accepting Terms and Conditions to use this Technology Service, you hereby confirm that you are placing order only for fulfillment of valid prescription.

You understand and agree that selling, stocking, or exhibiting, or offering for sale, or distribution of Medicines, if any, at Novus is only by the third party Independent Licensed Retail Store (hereinafter referred to as “Pharmacy”).
      `
    },
    {
      title: 'Tobacco Products',
      content: `
You agree and undertake that You will not use the Platform to transact for the purchase of Tobacco products on the Platform if You are below the age of eighteen years (twenty one if ordering in the state of Karnataka). While placing an order for tobacco products, You confirm that the delivery location is not within 100m of an Educational Institute. You also acknowledge that the delivery personnel may request a valid ID proof to confirm your age and that you shall comply with the request. Novus reserves the right to cancel your order in case of any transgressions.
      `
    },
    {
      title: 'Delivery',
      content: `
This website provides its services to the whole of India, subject to the following:

Delivery of prescribed medicines is done by Pharmacy against a valid prescription. The Pharmacy can refuse to deliver the order in absence of a valid prescription. Novus will not be held liable for refusal of orders by the Pharmacy.

Delivery of prescribed medicines, selected pharmaceutical and other related products is only available in Serviceable Pincodes as per logistics partner availability designated as "Serviceable Area".

Over the counter (OTC), health care and other related products except prescribed medicines will be available across all locations in India.

OTC, health care and other related products purchased from the website by a user located outside the serviceable area shall be delivered to the User by standard delivery partner services on behalf of the respective sellers through a logistics partner. If the standard delivery partner services are not available for a particular region/pin code, such order shall not be delivered and the user shall be intimated accordingly.

The Lab and Other Services shall be available only in the serviceable area as mentioned at the Novus from time to time.

This website is only for information and communication purposes. This website itself is not to sell, to stock, to exhibit or to offer for sale or to distribute medicines, pharmaceuticals, healthcare & other related products. We do not administer warranties or guarantees associated with the products or services. Nevertheless, any product warranty, offered by the manufacturer of the product as specified in the product specifications, will solely be their responsibility.

The data associated with the pharmaceutical and healthcare products and/or services provided on our website, Novus are solely for informative purposes and are not intended for commercialization. We have taken maximum care to ensure accuracy of the data. However, we do not guarantee cent per cent accuracy, as we have accumulated these data from external and third party sources. This should not be the basis for formulating any kind of decision without seeking professional advice.

No order for prescription medicine on the Novus website shall be or is being received without a valid Prescription. All the prescription orders and Prescription are forwarded to the Sellers who verify the Prescription through duly qualified endorsed registered pharmacists and approve the order and then only medicines are dispensed to the Users, as represented by the Sellers to Novus.

Information given here on various medicines and healthcare products and/or services is based on information related to Novus for publishing on the website by third parties and is mainly for informative purposes and is not intended for commercial use. As our website contains information that is created and maintained by a variety of external references / sources, we do not control or guarantee the information contained in / obtained from other external sources, and we do not specifically endorse any products or services offered therein. It is your responsibility to confirm the accuracy, completeness, and usefulness of all product information and to consult with your professional health care provider as to whether the information can benefit you. We assume no responsibility or liability for any consequence resulting directly or indirectly for any action or inaction you take based on or made in reliance on the information, services, or material on or linked to this website. It is imperative to seek professional advice before purchasing or consuming any medicine or healthcare product from the website. Further, you acknowledge that the content, text, data, graphics, images, information, suggestions, guidance, blogs, information and other materials that is provided to You on the Website should be used for information purposes only and do not constitute medical advice and should not be relied upon as a substitute for sound professional medical advice, evaluation or care from a doctor except for any advice, information or direction obtained by You directly from Your Doctor.

Due diligence will be exercised in removing drug(s) and healthcare product(s) and their related information from our website, on receipt of information about products being banned/ withdrawn/recalled by the Government of India or if any major health precaution / warning are issued on a product and any statutory mandate or regulatory guideline prohibits listing or sale of such products over the website. However, Novus takes no responsibility for any uninformed/misinformed/deliberate orders that are placed on the website with respect to such products before or during the process of delisting of the products under a statutory or regulatory order/guideline. Users are advised to remain informed before placing order or using product/services over the website and Users shall indemnify Novus for any claims, losses, damages etc arising out of such uninformed/misinformed/deliberate use of Products/Services by the Users.

No information received via this website should be treated as medical advice nor should be relied upon for any medical / pharmaceutical related decision and you should consult an appropriate professional for specific advice tailored to your situation.

The information provided here should not be treated as a substitute of medical advice given by your doctor and/or not to replace the advice of your doctor or the product information provided by the manufacturer of the products. Drug usage details (instructions) are provided on our website as sourced from third parties. We do not provide instructions for usage of the product. For the precise information on the product, the patient must see the product information available with each of the products and talk to his/her healthcare service provider / doctor.

Reference to specific products, processes, or services does not constitute or imply recommendation or endorsement by Novus. The Users must check with their own sources before acting upon and are encouraged and advised to confirm the information contained herein with other sources. The Health related topics found on this website should not be used for diagnosing purposes or be substituted for medical advice. Also, the information provided on this website is of a general nature only, and is not meant to replace the advice of your doctor or pharmacist or other healthcare provider. It is your responsibility to research the accuracy, completeness, and usefulness of all opinions, services, and other information found on this website, and to consult with your professional health care provider/doctor as to whether the information can benefit you. Please contact your healthcare provider/doctor for advice for your specific health or medical needs.

Novus assumes no responsibility or liability for any consequence resulting directly or indirectly for any action or inaction you take based on or made in reliance on the information, services, or material on or linked to this website.

We have placed responsibility on the sellers for listing products on the website, to take care that the products / medicines listed here are from approved licensed manufacturers. Novus shall not be responsible for any misbranded/spurious/adulterated products that any seller may list or sell through the website. There may be alternate brands available for the same product intended for specific medical conditions. Please consult your doctor in case you have questions on the exact product brand that you require. You may also talk to your doctor about alternative products / medicines. For all purposes and under all circumstances, you must leave all medical decisions related to the product and your health to your doctor.

All drug information provided here refers to generic pharmacology. Although reasonable care has been taken in verifying details provided on the products, as this information is taken from third parties, the website does not take any responsibility for accuracy for each brand, which may have different specification or usage for the same product and also does take any responsibility for meticulous precision inputs for brands, which have different specifications for the same product. The information provided here is only to help Users get a general view of the drug(s) they are consuming. The drug information provided on our website refers to the generic chemical content in the product and may not necessarily apply to the brand completely. Listing of Information that is specific to the brand or the sellers is the responsibility of the sellers on the website. The images shown here on the website are for illustration purposes only and may not be an exact representation of the product.
      `
    }
  ];